# Generated by Django 6.0 on 2026-02-18 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
    ]
